spring:
  application:
    name: register-sv
  kafka:
    bootstrap-servers: 127.0.0.1:32769
    consumer:
      group-id: test1

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/


config:
  kafka:
    topic: comp_info
