spring:
  application:
    name: register-sv
  kafka:
    bootstrap-servers: 35.240.203.70:2181
  datasource:
    url: jdbc:postgresql://database.ckcf3so2f9bc.ap-southeast-1.rds.amazonaws.com:5432/credential
    username: rkritchat
    password: 055090323
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://13.228.89.200/eureka/

config:
  kafka:
    topic: register

management:
  endpoints:
    web:
      base-path: /