spring:
  application:
    name: register-sv
  kafka:
    bootstrap-servers: 127.0.0.1:32768
  datasource:
    url: jdbc:postgresql://192.168.1.45:5432/credential
    username: postgres
    password: 055090323
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://register-sv:8762/eureka/

config:
  kafka:
    topic: comp_info

management:
  endpoints:
    web:
      base-path: /